data = [
    {'name': 'Cristiano Ronaldo', 'follower_count': 661, 'description': 'Footballer', 'country': 'Portugal'},
    {'name': 'Lionel Messi', 'follower_count': 506, 'description': 'Footballer', 'country': 'Argentina'},
    {'name': 'Selena Gomez', 'follower_count': 418, 'description': 'Musician and actress', 'country': 'USA'},
    {'name': 'Kylie Jenner', 'follower_count': 393, 'description': 'Media personality', 'country': 'USA'},
    {'name': 'Dwayne Johnson', 'follower_count': 393, 'description': 'Actor and wrestler', 'country': 'USA'},
    {'name': 'Ariana Grande', 'follower_count': 375, 'description': 'Musician and actress', 'country': 'USA'},
    {'name': 'Kim Kardashian', 'follower_count': 356, 'description': 'Media personality', 'country': 'USA'},
    {'name': 'Beyoncé', 'follower_count': 311, 'description': 'Musician and actress', 'country': 'USA'},
    {'name': 'Khloé Kardashian', 'follower_count': 302, 'description': 'Media personality', 'country': 'USA'},
    {'name': 'Justin Bieber', 'follower_count': 294, 'description': 'Musician', 'country': 'Canada'},
    {'name': 'Kendall Jenner', 'follower_count': 287, 'description': 'Media personality', 'country': 'USA'},
    {'name': 'Taylor Swift', 'follower_count': 281, 'description': 'Musician', 'country': 'USA'},
    {'name': 'Virat Kohli', 'follower_count': 274, 'description': 'Cricketer', 'country': 'India'},
    {'name': 'Jennifer Lopez', 'follower_count': 248, 'description': 'Musician and actress', 'country': 'USA'},
    {'name': 'Neymar Jr.', 'follower_count': 231, 'description': 'Footballer', 'country': 'Brazil'},
    {'name': 'Nicki Minaj', 'follower_count': 224, 'description': 'Musician', 'country': 'USA'},
    {'name': 'Kourtney Kardashian', 'follower_count': 218, 'description': 'Media personality', 'country': 'USA'},
    {'name': 'Miley Cyrus', 'follower_count': 212, 'description': 'Musician and actress', 'country': 'USA'},
    {'name': 'Katy Perry', 'follower_count': 204, 'description': 'Musician', 'country': 'USA'},
    {'name': 'Zendaya', 'follower_count': 178, 'description': 'Actress and singer', 'country': 'USA'},
    {'name': 'Kevin Hart', 'follower_count': 177, 'description': 'Comedian and actor', 'country': 'USA'},
    {'name': 'Cardi B', 'follower_count': 163, 'description': 'Musician and actress', 'country': 'USA'},
    {'name': 'LeBron James', 'follower_count': 159, 'description': 'Basketball player', 'country': 'USA'},
    {'name': 'Demi Lovato', 'follower_count': 153, 'description': 'Musician and actress', 'country': 'USA'},
    {'name': 'Rihanna', 'follower_count': 149, 'description': 'Musician', 'country': 'Barbados'},
    {'name': 'Chris Brown', 'follower_count': 144, 'description': 'Musician', 'country': 'USA'},
    {'name': 'Drake', 'follower_count': 142, 'description': 'Musician', 'country': 'Canada'},
    {'name': 'Gal Gadot', 'follower_count': 108, 'description': 'Actress', 'country': 'Israel'},
    {'name': 'Lisa (BLACKPINK)', 'follower_count': 106, 'description': 'Musician', 'country': 'Thailand'},
    {'name': 'Narendra Modi', 'follower_count': 96.2, 'description': 'Prime Minister', 'country': 'India'},
]
